name: Testing spiderchef

on:
  pull_request:
      branches:
          - main
          - develop
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Run typing/linting check
        run: make check
      - run: uv build
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl tests/smoke_test.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz tests/smoke_test.py
  pytest:
    strategy:
      matrix:
        py_version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.py_version }}
      - name: Run pytest check for Python ${{ matrix.py_version }}
        run: make test-ci
      - name: Show Coverage
        if: github.event_name == 'pull_request' && matrix.py_version == '3.12'
        uses: orgoro/coverage@v3.2
        with:
            coverageFile: coverage.xml
            thresholdAll: 0.90
            thresholdNew: 0.95
            token: ${{ secrets.GITHUB_TOKEN }}
